### ISSUE TITLE
How to handle with reserved fields?

### ISSUE THREAD

**Issue by olegario96** [jessicamrbr/jsons-to-cnab#1]
I'm trying to write an application to generate files for Bradesco bank, but in the Header file, the documentation says that a part of the record have exclusive fields for the bank:

![image](https://user-images.githubusercontent.com/15036437/54567461-a99a9f80-49b2-11e9-8516-b8abd232de1d.png)

In this cases, this is would be right JSON to use and using no mapping value?

```
{
        fieldName: "reservado_banco_01",
        positionStart: 172,
        positionEnd: 191,
        positionLength: 20,
        picture: "X"
        defaultValue: ""
}
```

**Comment by jessicamrbr** [comment]
When reserved for the bank, the manual usually says what the default value should be. In general for these fields, the default value included is pre-filled according to the picture.

To set the layout, it is apparently correct.

Please remember not to pass this attribute when set the data.
