### ISSUE TITLE
Add a special character to the fileTXT.crm

### ISSUE THREAD

**Issue by MarkDuarte** [jessicamrbr/jsons-to-cnab#23]
How do I add a special character to the fileTXT.crm? I need to add the file version CNAB of SICREDI, 
example: **2.00**

I tried putting the defaultValue: '2.00', but when I generate the CNAB file, the dot is replaced by a blank value.

**Comment by jessicamrbr** [comment]
if the field type is defined as integer or decimal, it will not accept the character "."
