### ISSUE TITLE
Remessa e Retorno de cecred (AILOS) 

### ISSUE THREAD

**Issue by tasca** [jessicamrbr/jsons-to-cnab#6]
Olá Jessica, vc tem remessa e retorno pronto pro cecred (AILOS) ?
Preciso em Nodejs, tô sem tempo pra desenvolver.
dependendo do custo, podemos cunversar !!!

tasca

**Comment by jessicamrbr** [comment]
https://www.linkedin.com/in/jéssica-moura-ribeiro-eng entra em contato podemos conversar para entender o que você precisa.

**Comment by jessicamrbr** [comment]
O projeto ainda não tem esses layouts, mas o mecanismo deve funcionar.
